// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn8JVbxvLHsuowH9QQD7siDYqrD0Tp1Rc',
    appId: '1:703815719485:web:ca488b4b5d9019f4326854',
    messagingSenderId: '703815719485',
    projectId: 'furniture-app-13a0a',
    authDomain: 'furniture-app-13a0a.firebaseapp.com',
    storageBucket: 'furniture-app-13a0a.appspot.com',
    measurementId: 'G-MLK74CZGVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD49GowhqeaVj41Lejjlk7oSOCUH1j-sDQ',
    appId: '1:703815719485:android:7555d0290a261aea326854',
    messagingSenderId: '703815719485',
    projectId: 'furniture-app-13a0a',
    storageBucket: 'furniture-app-13a0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB4g6cAtB4EWTeE9N2FwjU81eAce-C6n0',
    appId: '1:703815719485:ios:9225b3e09656836d326854',
    messagingSenderId: '703815719485',
    projectId: 'furniture-app-13a0a',
    storageBucket: 'furniture-app-13a0a.appspot.com',
    iosBundleId: 'com.example.furnitureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB4g6cAtB4EWTeE9N2FwjU81eAce-C6n0',
    appId: '1:703815719485:ios:2582500e308ae275326854',
    messagingSenderId: '703815719485',
    projectId: 'furniture-app-13a0a',
    storageBucket: 'furniture-app-13a0a.appspot.com',
    iosBundleId: 'com.example.furnitureApp.RunnerTests',
  );
}
