// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgsQ5DEaU32kWG-qyJIbZkqsHWEJtCWWE',
    appId: '1:1042010529441:web:206e9ebd900b65063fdae0',
    messagingSenderId: '1042010529441',
    projectId: 'chat-app-661bf',
    authDomain: 'chat-app-661bf.firebaseapp.com',
    storageBucket: 'chat-app-661bf.appspot.com',
    measurementId: 'G-GR0YWM31QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_T2K-dXBO-fPiRiTdiyT3kpT0k7VOijg',
    appId: '1:1042010529441:android:63c21c4624c4d0563fdae0',
    messagingSenderId: '1042010529441',
    projectId: 'chat-app-661bf',
    storageBucket: 'chat-app-661bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIDJ4hNCLQg9xwS0kv8fq8OokYi5Oso2g',
    appId: '1:1042010529441:ios:d338c14bf76ac7bc3fdae0',
    messagingSenderId: '1042010529441',
    projectId: 'chat-app-661bf',
    storageBucket: 'chat-app-661bf.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIDJ4hNCLQg9xwS0kv8fq8OokYi5Oso2g',
    appId: '1:1042010529441:ios:7af3c9c0264285d03fdae0',
    messagingSenderId: '1042010529441',
    projectId: 'chat-app-661bf',
    storageBucket: 'chat-app-661bf.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
